# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_animalkind'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='animal_kind',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='polls.AnimalKind'),
        ),
    ]
